In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('D:/JN/iNeuron/iNeuron_code/code_pandas1/examples/ex1.csv')
data

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [3]:
data = pd.read_csv(r'D:\JN\iNeuron\iNeuron_code\code_pandas1\examples\ex1.csv')
data

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [4]:
data = pd.read_csv(r'D:\JN\iNeuron\iNeuron_code\code_pandas1\examples\test.tsv')
data

              test\t test\ttest\ttest\ttest
0        sudh\tsudh\tsudh\tsudh\tsudh\tsudh
1  kumar\tkumar\tkumar\tkumar\tkumar\tkumar

In [6]:
data = pd.read_table(r'D:\JN\iNeuron\iNeuron_code\code_pandas1\examples\test.tsv')
data

        test   test test.1 test.2 test.3
sudh    sudh   sudh   sudh   sudh   sudh
kumar  kumar  kumar  kumar  kumar  kumar

In [5]:
path = "D:/JN/iNeuron/iNeuron_code/code_pandas1/examples/"

In [18]:
df =pd.read_csv(path+'ex2.csv', names=['asdfdsfs','fsdf', 'b', 'c', 'sudh', 'message'])
### names is used for only setting the column names
df

   asdfdsfs  fsdf   b   c   sudh  message
0         1     2   3   4  hello      NaN
1         5     6   7   8  world      NaN
2         9    10  11  12    foo      NaN

In [7]:
df =pd.read_csv(path+'ex2.csv', columns=['asdfdsfs','fsdf', 'b', 'c', 'sudh', 'message'])
### column keyword is used for df.to_csv()
#header is used for specifying the row to be the column name
df

TypeError: parser_f() got an unexpected keyword argument 'columns'

In [11]:
df =pd.read_csv(path+'ex2.csv', header=1)
df

   5   6   7   8 world
0  9  10  11  12   foo

In [26]:
parsed = pd.read_csv(path+'csv_mindex.csv')
parsed.head()

  key1 key2  value1  value2
0  one    a       1       2
1  one    b       3       4
2  one    c       5       6
3  one    d       7       8
4  two    a       9      10

In [12]:
parsed = pd.read_csv(path+'csv_mindex.csv', header=0, index_col=False)
### Indices can not be removed when reading. Can be edited by other name. Indices can be removed when writing to a file.
parsed

  key1 key2  value1  value2
0  one    a       1       2
1  one    b       3       4
2  one    c       5       6
3  one    d       7       8
4  two    a       9      10
5  two    b      11      12
6  two    c      13      14
7  two    d      15      16

In [31]:
parsed = pd.read_csv(path+'csv_mindex.csv', index_col=['key1','key2'])
parsed

           value1  value2
key1 key2
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

In [44]:
parsed[['value1']]

           value1
key1 key2
one  a          1
     b          3
     c          5
     d          7
two  a          9
     b         11
     c         13
     d         15

In [47]:
df = pd.read_csv(path+'ex4.csv', skiprows=[0,2,3])
df

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [50]:
df = pd.read_csv(path+'ex5.csv')
df.isnull()

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False   True  False    False
2      False  False  False  False  False    False

In [15]:
df = pd.read_csv(path+'ex5.csv', na_values=['NULL'])
df

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [16]:
df = pd.read_csv(path+'ex5.csv', keep_default_na=False)
df

  something  a   b   c   d message
0       one  1   2   3   4      NA
1       two  5   6       8   world
2     three  9  10  11  12     foo

In [18]:
url = "http://www.basketball-reference.com/leagues/NBA_2015_totals.html"
df = pd.read_html(url)
df

[      Rk          Player Pos Age   Tm   G  GS    MP   FG  FGA  ...   FT%  ORB  \
 0      1      Quincy Acy  PF  24  NYK  68  22  1287  152  331  ...  .784   79
 1      2    Jordan Adams  SG  20  MEM  30   0   248   35   86  ...  .609    9
 2      3    Steven Adams   C  21  OKC  70  67  1771  217  399  ...  .502  199
 3      4     Jeff Adrien  PF  28  MIN  17   0   215   19   44  ...  .579   23
 4      5   Arron Afflalo  SG  29  TOT  78  72  2502  375  884  ...  .843   27
 ..   ...             ...  ..  ..  ...  ..  ..   ...  ...  ...  ...   ...  ...
 670  490  Thaddeus Young  PF  26  TOT  76  68  2434  451  968  ...  .655  127
 671  490  Thaddeus Young  PF  26  MIN  48  48  1605  289  641  ...  .682   75
 672  490  Thaddeus Young  PF  26  BRK  28  20   829  162  327  ...  .606   52
 673  491     Cody Zeller   C  22  CHO  62  45  1487  172  373  ...  .774   97
 674  492    Tyler Zeller   C  25  BOS  82  59  1731  340  619  ...  .823  146

      DRB  TRB  AST  STL BLK  TOV   PF   PTS
 0    222  301   68   27  22   60  147   398
 1     19   28   16   16   7   14   24    94
 2    324  523   66   38  86   99  222   537
 3     54   77   15    4   9    9   30    60
 4    220  247  129   41   7  116  167  1035
 ..   ...  ...  ...  ...  ..  ...  ...   ...
 670  284  411  173  124  25  117  171  1071
 671  170  245  135   86  17   75  115   685
 672  114  166   38   38   8   42   56   386
 673  265  362  100   34  49   62  156   472
 674  319  465  113   18  52   76  205   833

 [675 rows x 30 columns]]

In [19]:
df[0]

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Quincy Acy,PF,24,NYK,68,22,1287,152,331,...,.784,79,222,301,68,27,22,60,147,398
1,2,Jordan Adams,SG,20,MEM,30,0,248,35,86,...,.609,9,19,28,16,16,7,14,24,94
2,3,Steven Adams,C,21,OKC,70,67,1771,217,399,...,.502,199,324,523,66,38,86,99,222,537
3,4,Jeff Adrien,PF,28,MIN,17,0,215,19,44,...,.579,23,54,77,15,4,9,9,30,60
4,5,Arron Afflalo,SG,29,TOT,78,72,2502,375,884,...,.843,27,220,247,129,41,7,116,167,1035
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,490,Thaddeus Young,PF,26,TOT,76,68,2434,451,968,...,.655,127,284,411,173,124,25,117,171,1071
671,490,Thaddeus Young,PF,26,MIN,48,48,1605,289,641,...,.682,75,170,245,135,86,17,75,115,685
672,490,Thaddeus Young,PF,26,BRK,28,20,829,162,327,...,.606,52,114,166,38,38,8,42,56,386
673,491,Cody Zeller,C,22,CHO,62,45,1487,172,373,...,.774,97,265,362,100,34,49,62,156,472
674,492,Tyler Zeller,C,25,BOS,82,59,1731,340,619,...,.823,146,319,465,113,18,52,76,205,833

In [23]:
df[0].iloc[:,0:20].head(5)

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,2P%,eFG%,FT,FTA
0,1,Quincy Acy,PF,24,NYK,68,22,1287,152,331,.459,18,60,.300,134,271,.494,.486,76,97
1,2,Jordan Adams,SG,20,MEM,30,0,248,35,86,.407,10,25,.400,25,61,.410,.465,14,23
2,3,Steven Adams,C,21,OKC,70,67,1771,217,399,.544,0,2,.000,217,397,.547,.544,103,205
3,4,Jeff Adrien,PF,28,MIN,17,0,215,19,44,.432,0,0,NaN,19,44,.432,.432,22,38
4,5,Arron Afflalo,SG,29,TOT,78,72,2502,375,884,.424,118,333,.354,257,551,.466,.491,167,198

In [32]:
path = 'https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/'
titanic = pd.read_csv(path+'titanic.csv', sep='\t')
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

In [31]:
path = 'https://gist.github.com/michhar/2dfd2de0d4f8727f873422c5d959fff5'
titanic2 = pd.read_html(path)
titanic2[0]

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,NaN,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,NaN,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,NaN,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,NaN,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,NaN,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,NaN,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,NaN,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,NaN,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,NaN,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,NaN,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [33]:
path = 'https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/'
titanic = pd.read_csv(path+'titanic.csv', sep='\t')
titanic.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [41]:
pd.options.display.max_rows = 10  ### It dows not load all the data together, rather display only desired number of rows

In [42]:
path = "D:/JN/iNeuron/iNeuron_code/code_pandas1/examples/"
result = pd.read_csv(path+'ex6.csv')
result

           one       two     three      four key
0     0.467976 -0.038649 -0.295344 -1.824726   L
1    -0.358893  1.404453  0.704965 -0.200638   B
2    -0.501840  0.659254 -0.421691 -0.057688   G
3     0.204886  1.074134  1.388361 -0.982404   R
4     0.354628 -0.133116  0.283763 -0.837063   Q
...        ...       ...       ...       ...  ..
9995  2.311896 -0.417070 -1.409599 -0.515821   L
9996 -0.479893 -0.650419  0.745152 -0.646038   E
9997  0.523331  0.787112  0.486066  1.093156   K
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

[10000 rows x 5 columns]

In [43]:
result = pd.read_(path+'ex6.csv', nrows=5)
result

        one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G
3  0.204886  1.074134  1.388361 -0.982404   R
4  0.354628 -0.133116  0.283763 -0.837063   Q

In [44]:
result = pd.read_csv(path+'ex6.csv', chunksize=500)
result

In [4]:
path = "D:/JN/iNeuron/iNeuron_code/code_pandas1/examples/"
result = pd.read_csv(path+'fasta_file.txt')
result

                                  >Example_1(Q16778)
0  MPEPAKSAPAPKKGSKKAVTKAQKKDGKKRKRSRKESYSIYVYKVL...
1  GIMNSFVNDIFERIAGEASRLAHYNKRSTITSREIQTAVRLLLPGE...
2                                             KYTSSK
3                                 >Example_2(P68431)
4  MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGT...
5  LIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFED...
6                                     KDIQLARRIRGERA

In [6]:
result.to_csv(path+'fasta_file2.fasta', index=None)

In [37]:
path = r'G:\G Drive\Thesis Paper\Bioinformatics(sabit)\Protein\PTM\Phosphoglycerylation'

df = pd.read_csv(path+'\\dataset.txt',sep='\n', names=['Protein ID','Sites','Bigram-PGK','Phogly_PseAAC','CKSAAP_PhoglySite','iPGK_PseAAC'], skiprows=[0,1,2,3,4,5])

b= df.iloc[0,0].rstrip('\'')
b = df.iloc[0,0][1:]
b

"Q3UJB0'"

In [42]:
path = r'G:\G Drive\Thesis Paper\Bioinformatics(sabit)\Protein\PTM\Phosphoglycerylation'

df = pd.read_csv(path+'\\dataset.txt',sep='\n', names=['Protein ID','Sites','Bigram-PGK','Phogly_PseAAC','CKSAAP_PhoglySite','iPGK_PseAAC'], skiprows=[0,1,2,3,4,5])
a=[]
for i in range(len(df)):
    if len(df.iloc[i,0])>1:
        if df.iloc[i,0][0] == "'" and df.iloc[i,0][7] == "'":
            ch = df.iloc[i,0][1:7]
        elif df.iloc[i,0][0] == "'":
            ch = df.iloc[i,0][1:]
        elif df.iloc[i,0][6] == "'":
            ch = df.iloc[i,0][0:6]
        a.append(ch)

In [22]:
len(df.iloc[0,0])

8

In [43]:
a=pd.DataFrame(a)
a

         0
0   Q3UJB0
1   E9QMI7
2   P47857
3   Q920E5
4   Q9C026
..     ...
86  P35585
87  P62814
88  Q80ZV3
89  B8ZZL8
90  Q6PKG0

[91 rows x 1 columns]

In [44]:
a.to_csv(path+"\\PID.txt", header=None, index=None)

In [3]:
import pandas as pd
phogly = pd.read_html('Phosphoglycerylation Result.html')

ValueError: No tables found

In [13]:
dates = pd.date_range('20-08-2020',  periods=7, freq='2H')
dates

DatetimeIndex(['2020-08-20 00:00:00', '2020-08-20 02:00:00',
               '2020-08-20 04:00:00', '2020-08-20 06:00:00',
               '2020-08-20 08:00:00', '2020-08-20 10:00:00',
               '2020-08-20 12:00:00'],
              dtype='datetime64[ns]', freq='2H')

In [20]:
import numpy as np
ser = pd.Series(np.arange(7), index=dates)
ser

2020-08-20 00:00:00    0
2020-08-20 02:00:00    1
2020-08-20 04:00:00    2
2020-08-20 06:00:00    3
2020-08-20 08:00:00    4
2020-08-20 10:00:00    5
2020-08-20 12:00:00    6
Freq: 2H, dtype: int32

In [21]:
import numpy as np
ser = pd.DataFrame(np.arange(7), index=dates)
ser

                     0
2020-08-20 00:00:00  0
2020-08-20 02:00:00  1
2020-08-20 04:00:00  2
2020-08-20 06:00:00  3
2020-08-20 08:00:00  4
2020-08-20 10:00:00  5
2020-08-20 12:00:00  6

In [43]:
f1=pd.read_csv(r'D:\JN\iNeuron\iNeuron_code\code_pandas1\examples\ex5.csv')
f1

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [29]:
import csv

f=open(r'D:\JN\iNeuron\iNeuron_code\code_pandas1\examples\ex5.csv')

reader = csv.reader(f)
list(reader)

[['something', 'a', 'b', 'c', 'd', 'message'],
 ['one', '1', '2', '3', '4', 'NA'],
 ['two', '5', '6', '', '8', 'world'],
 ['three', '9', '10', '11', '12', 'foo']]

In [25]:
for i in reader:
    print(i)

['something', 'a', 'b', 'c', 'd', 'message']
['one', '1', '2', '3', '4', 'NA']
['two', '5', '6', '', '8', 'world']
['three', '9', '10', '11', '12', 'foo']

In [30]:
with open(r'D:\JN\iNeuron\iNeuron_code\code_pandas1\examples\ex5.csv') as f:
    lines = list(csv.reader(f))
lines

[['something', 'a', 'b', 'c', 'd', 'message'],
 ['one', '1', '2', '3', '4', 'NA'],
 ['two', '5', '6', '', '8', 'world'],
 ['three', '9', '10', '11', '12', 'foo']]

In [35]:
header, values = lines[0], lines[1:]
header

['something', 'a', 'b', 'c', 'd', 'message']

In [36]:
values

[['one', '1', '2', '3', '4', 'NA'],
 ['two', '5', '6', '', '8', 'world'],
 ['three', '9', '10', '11', '12', 'foo']]

In [39]:
a = zip(header,values)
a

In [40]:
b=list(zip(header,values))
b

[('something', ['one', '1', '2', '3', '4', 'NA']),
 ('a', ['two', '5', '6', '', '8', 'world']),
 ('b', ['three', '9', '10', '11', '12', 'foo'])]

In [41]:
c=list(zip(header,*values))
c

[('something', 'one', 'two', 'three'),
 ('a', '1', '5', '9'),
 ('b', '2', '6', '10'),
 ('c', '3', '', '11'),
 ('d', '4', '8', '12'),
 ('message', 'NA', 'world', 'foo')]

In [44]:
d=list(zip(header,zip(*values)))
d

[('something', ('one', 'two', 'three')),
 ('a', ('1', '5', '9')),
 ('b', ('2', '6', '10')),
 ('c', ('3', '', '11')),
 ('d', ('4', '8', '12')),
 ('message', ('NA', 'world', 'foo'))]

In [46]:
data_dict = {h:v for h,v in zip(header,values)}
data_dict

{'something': ['one', '1', '2', '3', '4', 'NA'],
 'a': ['two', '5', '6', '', '8', 'world'],
 'b': ['three', '9', '10', '11', '12', 'foo']}

In [51]:
data_dict = {h:v for h,v in zip(header,zip(*values))}
data_dict

{'something': ('one', 'two', 'three'),
 'a': ('1', '5', '9'),
 'b': ('2', '6', '10'),
 'c': ('3', '', '11'),
 'd': ('4', '8', '12'),
 'message': ('NA', 'world', 'foo')}

JSON

In [52]:
obj = """
{"name": "Wes",
 "places_lived": ["United States", "Spain", "Germany"],
 "pet": null,
 "siblings": [{"name": "Scott", "age": 30, "pets": ["Zeus", "Zuko"]},
              {"name": "Katie", "age": 38,
               "pets": ["Sixes", "Stache", "Cisco"]}]
}
"""

In [58]:
type(obj)

str

In [61]:
obj

'\n{"name": "Wes",\n "places_lived": ["United States", "Spain", "Germany"],\n "pet": null,\n "siblings": [{"name": "Scott", "age": 30, "pets": ["Zeus", "Zuko"]},\n              {"name": "Katie", "age": 38,\n               "pets": ["Sixes", "Stache", "Cisco"]}]\n}\n'

In [55]:
import json
f = json.loads(obj)
f

{'name': 'Wes',
 'places_lived': ['United States', 'Spain', 'Germany'],
 'pet': None,
 'siblings': [{'name': 'Scott', 'age': 30, 'pets': ['Zeus', 'Zuko']},
  {'name': 'Katie', 'age': 38, 'pets': ['Sixes', 'Stache', 'Cisco']}]}

In [57]:
type(f)

dict

In [59]:
b=json.dumps(f)
b

'{"name": "Wes", "places_lived": ["United States", "Spain", "Germany"], "pet": null, "siblings": [{"name": "Scott", "age": 30, "pets": ["Zeus", "Zuko"]}, {"name": "Katie", "age": 38, "pets": ["Sixes", "Stache", "Cisco"]}]}'

In [60]:
type(b)

str

In [62]:
s = pd.DataFrame(f)
s

ValueError: arrays must all be same length

In [63]:
s = pd.DataFrame(f['places_lived'])
s

               0
0  United States
1          Spain
2        Germany

In [64]:
s = pd.DataFrame(f['siblings'])
s

    name  age                    pets
0  Scott   30            [Zeus, Zuko]
1  Katie   38  [Sixes, Stache, Cisco]

In [65]:
s = pd.DataFrame(f['siblings'][0])
s

    name  age  pets
0  Scott   30  Zeus
1  Scott   30  Zuko

In [66]:
s = pd.DataFrame(f['siblings'][1])
s

    name  age    pets
0  Katie   38   Sixes
1  Katie   38  Stache
2  Katie   38   Cisco

In [67]:
s = pd.DataFrame(f['siblings'][0]['pets'])
s

      0
0  Zeus
1  Zuko

In [68]:
s = pd.DataFrame(f['siblings'], columns = ['name', 'age', 'pets'])
s

    name  age                    pets
0  Scott   30            [Zeus, Zuko]
1  Katie   38  [Sixes, Stache, Cisco]

In [69]:
s = pd.DataFrame(f['siblings'], columns = ['name', 'pets'])
s

    name                    pets
0  Scott            [Zeus, Zuko]
1  Katie  [Sixes, Stache, Cisco]

In [70]:
data = pd.read_json(r'D:\JN\iNeuron\iNeuron_code\code_pandas1\examples\example.json')
data

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [71]:
print(data.to_json())
print(data.to_json(orient='records'))

{"a":{"0":1,"1":4,"2":7},"b":{"0":2,"1":5,"2":8},"c":{"0":3,"1":6,"2":9}}
[{"a":1,"b":2,"c":3},{"a":4,"b":5,"c":6},{"a":7,"b":8,"c":9}]

In [74]:
tables = pd.read_html(r'D:\JN\iNeuron\iNeuron_code\code_pandas1\examples\fdic_failed_bank_list.html')
len(tables)
failures = tables[0]
failures

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
0,Allied Bank,Mulberry,AR,91,Today's Bank,"September 23, 2016","November 17, 2016"
1,The Woodbury Banking Company,Woodbury,GA,11297,United Bank,"August 19, 2016","November 17, 2016"
2,First CornerStone Bank,King of Prussia,PA,35312,First-Citizens Bank & Trust Company,"May 6, 2016","September 6, 2016"
3,Trust Company Bank,Memphis,TN,9956,The Bank of Fayette County,"April 29, 2016","September 6, 2016"
4,North Milwaukee State Bank,Milwaukee,WI,20364,First-Citizens Bank & Trust Company,"March 11, 2016","June 16, 2016"
...,...,...,...,...,...,...,...
542,"Superior Bank, FSB",Hinsdale,IL,32646,"Superior Federal, FSB","July 27, 2001","August 19, 2014"
543,Malta National Bank,Malta,OH,6629,North Valley Bank,"May 3, 2001","November 18, 2002"
544,First Alliance Bank & Trust Co.,Manchester,NH,34264,Southern New Hampshire Bank & Trust,"February 2, 2001","February 18, 2003"
545,National State Bank of Metropolis,Metropolis,IL,3815,Banterra Bank of Marion,"December 14, 2000","March 17, 2005"
546,Bank of Honolulu,Honolulu,HI,21029,Bank of the Orient,"October 13, 2000","March 17, 2005"

In [73]:
close_timestamps = pd.to_datetime(failures['Closing Date'])
close_timestamps.dt.year.value_counts()
#close_timestamps

2010    157
2009    140
2011     92
2012     51
2008     25
2013     24
2014     18
2002     11
2015      8
2016      5
2004      4
2001      4
2007      3
2003      3
2000      2
Name: Closing Date, dtype: int64

In [75]:
close_timestamps

0     2016-09-23
1     2016-08-19
2     2016-05-06
3     2016-04-29
4     2016-03-11
         ...
542   2001-07-27
543   2001-05-03
544   2001-02-02
545   2000-12-14
546   2000-10-13
Name: Closing Date, Length: 547, dtype: datetime64[ns]

In [90]:
frame = pd.DataFrame({'a':np.random.randn(100)})
store = pd.HDFStore('ABC.h5')
store['abc'] = frame
store

<class 'pandas.io.pytables.HDFStore'>
File path: ABC.h5

In [91]:
store['abc']

           a
0   0.114351
1   0.056094
2   1.237988
3  -0.525767
4  -0.882699
..       ...
95 -1.163246
96 -0.558432
97  2.409651
98 -0.451503
99 -1.089713

[100 rows x 1 columns]

In [88]:
store2 = pd.HDFStore('DEF.h5')
store2['cde'] = frame['a']
store2

<class 'pandas.io.pytables.HDFStore'>
File path: DEF.h5

In [89]:
store['cde']

0    0.884764
1    0.972819
2    0.128197
3   -0.649982
4    0.047735
Name: a, dtype: float64

In [94]:
store.put('obj2', frame, format='table')
store.select('obj2', where=['index >= 10 and index <= 15'])
store.close()

ClosedFileError: ABC.h5 file is not open!

In [95]:
frame.to_hdf('mydata.h5', 'obj3', format='table')

In [97]:
pd.read_hdf('mydata.h5')

           a
0   0.114351
1   0.056094
2   1.237988
3  -0.525767
4  -0.882699
..       ...
95 -1.163246
96 -0.558432
97  2.409651
98 -0.451503
99 -1.089713

[100 rows x 1 columns]

In [103]:
frame.to_hdf('ABC2.h5', 'obj1',format='table')

In [104]:
pd.read_hdf('ABC2.h5')

           a
0   0.114351
1   0.056094
2   1.237988
3  -0.525767
4  -0.882699
..       ...
95 -1.163246
96 -0.558432
97  2.409651
98 -0.451503
99 -1.089713

[100 rows x 1 columns]

# Web API

In [4]:
import requests

url='https://api.github.com/repos/pandas-dev/pandas/issues'
r=requests.get(url)
r

In [5]:
r.json()

[{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35839',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35839/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35839/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35839/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/35839',
  'id': 683248743,
  'node_id': 'MDExOlB1bGxSZXF1ZXN0NDcxMzY3Nzcw',
  'number': 35839,
  'title': 'REF: remove unnecesary try/except',
  'user': {'login': 'jbrockmendel',
   'id': 8078968,
   'node_id': 'MDQ6VXNlcjgwNzg5Njg=',
   'avatar_url': 'https://avatars1.githubusercontent.com/u/8078968?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/jbrockmendel',
   'html_url': 'https://github.com/jbrockmendel',
   'followers_url': 'https://api.github.com/users/jbrockmendel/followers',
   'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}',
   'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions',
   'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs',
   'repos_url': 'https://api.github.com/users/jbrockmendel/repos',
   'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2020-08-21T04:19:57Z',
  'updated_at': '2020-08-21T04:19:57Z',
  'closed_at': None,
  'author_association': 'MEMBER',
  'active_lock_reason': None,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/35839',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/35839',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/35839.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/35839.patch'},
  'body': 'and make cast_result_block into cast_agg_result operate on values instead of blocks',
  'performed_via_github_app': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35838',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35838/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35838/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35838/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/35838',
  'id': 683227415,
  'node_id': 'MDExOlB1bGxSZXF1ZXN0NDcxMzUwMjQy',
  'number': 35838,
  'title': 'Fix Series construction from Sparse["datetime64[ns]"]',
  'user': {'login': 'dsaxton',
   'id': 2658661,
   'node_id': 'MDQ6VXNlcjI2NTg2NjE=',
   'avatar_url': 'https://avatars0.githubusercontent.com/u/2658661?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/dsaxton',
   'html_url': 'https://github.com/dsaxton',
   'followers_url': 'https://api.github.com/users/dsaxton/followers',
   'following_url': 'https://api.github.com/users/dsaxton/following{/other_user}',
   'gists_url': 'https://api.github.com/users/dsaxton/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/dsaxton/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/dsaxton/subscriptions',
   'organizations_url': 'https://api.github.com/users/dsaxton/orgs',
   'repos_url': 'https://api.github.com/users/dsaxton/repos',
   'events_url': 'https://api.github.com/users/dsaxton/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/dsaxton/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 76811,
    'node_id': 'MDU6TGFiZWw3NjgxMQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',
    'name': 'Bug',
    'color': 'e10c02',
    'default': False,
    'description': None},
   {'id': 1465286368,
    'node_id': 'MDU6TGFiZWwxNDY1Mjg2MzY4',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Constructors',
    'name': 'Constructors',
    'color': 'd4c5f9',
    'default': False,
    'description': 'Series/DataFrame/Index/pd.array Constructors'},
   {'id': 49182326,
    'node_id': 'MDU6TGFiZWw0OTE4MjMyNg==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Sparse',
    'name': 'Sparse',
    'color': '009800',
    'default': False,
    'description': 'Sparse Data Type'},
   {'id': 211840,
    'node_id': 'MDU6TGFiZWwyMTE4NDA=',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Timeseries',
    'name': 'Timeseries',
    'color': 'AFEEEE',
    'default': False,
    'description': None}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2020-08-21T03:15:17Z',
  'updated_at': '2020-08-21T03:16:05Z',
  'closed_at': None,
  'author_association': 'CONTRIBUTOR',
  'active_lock_reason': None,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/35838',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/35838',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/35838.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/35838.patch'},
  'body': '- [x] tests added / passed\r\n- [x] passes `black pandas`\r\n- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`\r\n- [x] whatsnew entry\r\n\r\nxref #35762',
  'performed_via_github_app': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35837',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35837/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35837/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35837/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/35837',
  'id': 683178499,
  'node_id': 'MDExOlB1bGxSZXF1ZXN0NDcxMzEwMzU4',
  'number': 35837,
  'title': 'Update SparseDtype user guide doc',
  'user': {'login': 'dsaxton',
   'id': 2658661,
   'node_id': 'MDQ6VXNlcjI2NTg2NjE=',
   'avatar_url': 'https://avatars0.githubusercontent.com/u/2658661?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/dsaxton',
   'html_url': 'https://github.com/dsaxton',
   'followers_url': 'https://api.github.com/users/dsaxton/followers',
   'following_url': 'https://api.github.com/users/dsaxton/following{/other_user}',
   'gists_url': 'https://api.github.com/users/dsaxton/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/dsaxton/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/dsaxton/subscriptions',
   'organizations_url': 'https://api.github.com/users/dsaxton/orgs',
   'repos_url': 'https://api.github.com/users/dsaxton/repos',
   'events_url': 'https://api.github.com/users/dsaxton/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/dsaxton/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2020-08-21T00:40:57Z',
  'updated_at': '2020-08-21T00:40:57Z',
  'closed_at': None,
  'author_association': 'CONTRIBUTOR',
  'active_lock_reason': None,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/35837',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/35837',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/35837.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/35837.patch'},
  'body': 'Tiny doc nit. The doc says you can pass both dtype and fill_value to SparseDtype then only passes one in the example.',
  'performed_via_github_app': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35836',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35836/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35836/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35836/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/35836',
  'id': 683177299,
  'node_id': 'MDExOlB1bGxSZXF1ZXN0NDcxMzA5Mzc5',
  'number': 35836,
  'title': 'CI: avoid file leak from ipython tests',
  'user': {'login': 'jbrockmendel',
   'id': 8078968,
   'node_id': 'MDQ6VXNlcjgwNzg5Njg=',
   'avatar_url': 'https://avatars1.githubusercontent.com/u/8078968?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/jbrockmendel',
   'html_url': 'https://github.com/jbrockmendel',
   'followers_url': 'https://api.github.com/users/jbrockmendel/followers',
   'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}',
   'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions',
   'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs',
   'repos_url': 'https://api.github.com/users/jbrockmendel/repos',
   'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2020-08-21T00:37:00Z',
  'updated_at': '2020-08-21T01:55:38Z',
  'closed_at': None,
  'author_association': 'MEMBER',
  'active_lock_reason': None,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/35836',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/35836',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/35836.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/35836.patch'},
  'body': 'Broken off from #35711',
  'performed_via_github_app': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35835',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35835/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35835/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35835/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/35835',
  'id': 683154790,
  'node_id': 'MDExOlB1bGxSZXF1ZXN0NDcxMjkwNTQy',
  'number': 35835,
  'title': 'MAINT: Manual Backport PR #35825 on branch 1.1.x',
  'user': {'login': 'alimcmaster1',
   'id': 16733618,
   'node_id': 'MDQ6VXNlcjE2NzMzNjE4',
   'avatar_url': 'https://avatars1.githubusercontent.com/u/16733618?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/alimcmaster1',
   'html_url': 'https://github.com/alimcmaster1',
   'followers_url': 'https://api.github.com/users/alimcmaster1/followers',
   'following_url': 'https://api.github.com/users/alimcmaster1/following{/other_user}',
   'gists_url': 'https://api.github.com/users/alimcmaster1/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/alimcmaster1/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/alimcmaster1/subscriptions',
   'organizations_url': 'https://api.github.com/users/alimcmaster1/orgs',
   'repos_url': 'https://api.github.com/users/alimcmaster1/repos',
   'events_url': 'https://api.github.com/users/alimcmaster1/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/alimcmaster1/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 32933285,
    'node_id': 'MDU6TGFiZWwzMjkzMzI4NQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Admin',
    'name': 'Admin',
    'color': 'DDDDDD',
    'default': False,
    'description': 'Administrative tasks related to the pandas project'},
   {'id': 48070600,
    'node_id': 'MDU6TGFiZWw0ODA3MDYwMA==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/CI',
    'name': 'CI',
    'color': 'a2bca7',
    'default': False,
    'description': 'Related to Continuous Integration'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': {'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/76',
   'html_url': 'https://github.com/pandas-dev/pandas/milestone/76',
   'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/76/labels',
   'id': 5781056,
   'node_id': 'MDk6TWlsZXN0b25lNTc4MTA1Ng==',
   'number': 76,
   'title': '1.1.2',
   'description': 'on-merge: backport to 1.1.x',
   'creator': {'login': 'simonjayhawkins',
    'id': 13159005,
    'node_id': 'MDQ6VXNlcjEzMTU5MDA1',
    'avatar_url': 'https://avatars0.githubusercontent.com/u/13159005?v=4',
    'gravatar_id': '',
    'url': 'https://api.github.com/users/simonjayhawkins',
    'html_url': 'https://github.com/simonjayhawkins',
    'followers_url': 'https://api.github.com/users/simonjayhawkins/followers',
    'following_url': 'https://api.github.com/users/simonjayhawkins/following{/other_user}',
    'gists_url': 'https://api.github.com/users/simonjayhawkins/gists{/gist_id}',
    'starred_url': 'https://api.github.com/users/simonjayhawkins/starred{/owner}{/repo}',
    'subscriptions_url': 'https://api.github.com/users/simonjayhawkins/subscriptions',
    'organizations_url': 'https://api.github.com/users/simonjayhawkins/orgs',
    'repos_url': 'https://api.github.com/users/simonjayhawkins/repos',
    'events_url': 'https://api.github.com/users/simonjayhawkins/events{/privacy}',
    'received_events_url': 'https://api.github.com/users/simonjayhawkins/received_events',
    'type': 'User',
    'site_admin': False},
   'open_issues': 27,
   'closed_issues': 3,
   'state': 'open',
   'created_at': '2020-08-17T19:11:56Z',
   'updated_at': '2020-08-21T00:36:03Z',
   'due_on': '2020-09-06T07:00:00Z',
   'closed_at': None},
  'comments': 1,
  'created_at': '2020-08-20T23:28:05Z',
  'updated_at': '2020-08-21T00:39:49Z',
  'closed_at': None,
  'author_association': 'CONTRIBUTOR',
  'active_lock_reason': None,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/35835',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/35835',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/35835.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/35835.patch'},
  'body': 'Manual backport of below\r\n\r\nRef: https://github.com/pandas-dev/pandas/pull/35828#issuecomment-677917854\r\n\r\nThis is because we dropped 3.6 support on master (https://github.com/pandas-dev/pandas/pull/35214)\r\n\r\ncc @simonjayhawkins \r\n',
  'performed_via_github_app': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35834',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35834/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35834/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35834/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/35834',
  'id': 683130320,
  'node_id': 'MDExOlB1bGxSZXF1ZXN0NDcxMjY5OTY2',
  'number': 35834,
  'title': 'Backport PR #35825 on branch 1.1.x (DOC: Start 1.1.2)',
  'user': {'login': 'meeseeksmachine',
   'id': 39504233,
   'node_id': 'MDQ6VXNlcjM5NTA0MjMz',
   'avatar_url': 'https://avatars0.githubusercontent.com/u/39504233?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/meeseeksmachine',
   'html_url': 'https://github.com/meeseeksmachine',
   'followers_url': 'https://api.github.com/users/meeseeksmachine/followers',
   'following_url': 'https://api.github.com/users/meeseeksmachine/following{/other_user}',
   'gists_url': 'https://api.github.com/users/meeseeksmachine/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/meeseeksmachine/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/meeseeksmachine/subscriptions',
   'organizations_url': 'https://api.github.com/users/meeseeksmachine/orgs',
   'repos_url': 'https://api.github.com/users/meeseeksmachine/repos',
   'events_url': 'https://api.github.com/users/meeseeksmachine/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/meeseeksmachine/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 134699,
    'node_id': 'MDU6TGFiZWwxMzQ2OTk=',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Docs',
    'name': 'Docs',
    'color': '3465A4',
    'default': False,
    'description': None}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': {'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/76',
   'html_url': 'https://github.com/pandas-dev/pandas/milestone/76',
   'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/76/labels',
   'id': 5781056,
   'node_id': 'MDk6TWlsZXN0b25lNTc4MTA1Ng==',
   'number': 76,
   'title': '1.1.2',
   'description': 'on-merge: backport to 1.1.x',
   'creator': {'login': 'simonjayhawkins',
    'id': 13159005,
    'node_id': 'MDQ6VXNlcjEzMTU5MDA1',
    'avatar_url': 'https://avatars0.githubusercontent.com/u/13159005?v=4',
    'gravatar_id': '',
    'url': 'https://api.github.com/users/simonjayhawkins',
    'html_url': 'https://github.com/simonjayhawkins',
    'followers_url': 'https://api.github.com/users/simonjayhawkins/followers',
    'following_url': 'https://api.github.com/users/simonjayhawkins/following{/other_user}',
    'gists_url': 'https://api.github.com/users/simonjayhawkins/gists{/gist_id}',
    'starred_url': 'https://api.github.com/users/simonjayhawkins/starred{/owner}{/repo}',
    'subscriptions_url': 'https://api.github.com/users/simonjayhawkins/subscriptions',
    'organizations_url': 'https://api.github.com/users/simonjayhawkins/orgs',
    'repos_url': 'https://api.github.com/users/simonjayhawkins/repos',
    'events_url': 'https://api.github.com/users/simonjayhawkins/events{/privacy}',
    'received_events_url': 'https://api.github.com/users/simonjayhawkins/received_events',
    'type': 'User',
    'site_admin': False},
   'open_issues': 27,
   'closed_issues': 3,
   'state': 'open',
   'created_at': '2020-08-17T19:11:56Z',
   'updated_at': '2020-08-21T00:36:03Z',
   'due_on': '2020-09-06T07:00:00Z',
   'closed_at': None},
  'comments': 1,
  'created_at': '2020-08-20T22:19:11Z',
  'updated_at': '2020-08-20T23:31:08Z',
  'closed_at': None,
  'author_association': 'NONE',
  'active_lock_reason': None,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/35834',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/35834',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/35834.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/35834.patch'},
  'body': 'Backport PR #35825: DOC: Start 1.1.2',
  'performed_via_github_app': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35833',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35833/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35833/comments',

In [6]:
data = r.json()
data[0]['url']

'https://api.github.com/repos/pandas-dev/pandas/issues/35839'

In [36]:
issues = pd.DataFrame(data, columns=['number','title','labels', 'state'])
issues

,number,title,labels,state
0,35839,REF: remove unnecesary try/except,[],open
1,35838,"Fix Series construction from Sparse[""datetime6...","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
2,35837,Update SparseDtype user guide doc,[],open
3,35836,CI: avoid file leak from ipython tests,[],open
4,35835,MAINT: Manual Backport PR #35825 on branch 1.1.x,"[{'id': 32933285, 'node_id': 'MDU6TGFiZWwzMjkz...",open
5,35834,Backport PR #35825 on branch 1.1.x (DOC: Start...,"[{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...",open
6,35833,Backport PR #35757 on branch 1.1.x (CI: Unpin ...,"[{'id': 48070600, 'node_id': 'MDU6TGFiZWw0ODA3...",open
7,35832,Jsonlines append mode,[],open
8,35831,RLS: 1.1.2,"[{'id': 131473665, 'node_id': 'MDU6TGFiZWwxMzE...",open
9,35830,BUG: read_excel with index_col as as datetime,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
10,35829,Fix unable to build Pandas with xlc on z/OS,"[{'id': 129350, 'node_id': 'MDU6TGFiZWwxMjkzNT...",open
11,35826,BUG: Unable to build Pandas on z/OS when using...,"[{'id': 129350, 'node_id': 'MDU6TGFiZWwxMjkzNT...",open
12,35824,CI/DOC: unpin gitdb #35823,"[{'id': 48070600, 'node_id': 'MDU6TGFiZWw0ODA3...",open
13,35823,"CI/DOC: unpin gitdb, use gitdb instead of gitdb2","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
14,35820,QST: CSV read issue,"[{'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOT...",open
15,35819,QST:Time index problem in version 1.1.0,"[{'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOT...",open
16,35818,"BUG: Dataframe.apply(func, axis=1) when func r...","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
17,35816,BUG: read_excel doesn't honor dtype for index,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
18,35814,TST: Fix test_parquet failures for pyarrow 1.0,"[{'id': 685114413, 'node_id': 'MDU6TGFiZWw2ODU...",open
19,35811,QST: Series.transform with a dictionary,"[{'id': 35818298, 'node_id': 'MDU6TGFiZWwzNTgx...",open
20,35807,BUG: Issue with Pandas df.str.split with expand,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
21,35805,Performance regression in index_object.IndexEq...,"[{'id': 8935311, 'node_id': 'MDU6TGFiZWw4OTM1M...",open
22,35804,Performance regression in reindex.LevelAlign.t...,"[{'id': 8935311, 'node_id': 'MDU6TGFiZWw4OTM1M...",open
23,35803,Performance regression in tslibs.tz_convert.Ti...,"[{'id': 732775912, 'node_id': 'MDU6TGFiZWw3MzI...",open
24,35802,BUG: Was trying to read an ods file and ran in...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
25,35799,TST: resample does not yield empty groups (#10...,[],open
26,35798,Bump asv Python version,"[{'id': 732775912, 'node_id': 'MDU6TGFiZWw3MzI...",open
27,35797,Fix is_categorical_dtype for Sparse[category],"[{'id': 78527356, 'node_id': 'MDU6TGFiZWw3ODUy...",open
28,35796,ENH:dataframe columns dropping with column nam...,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...",open
29,35795,BUG: pd.DataFrame.astype for SparseDtype with ...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open

KeyError: 0

In [11]:
labels = pd.DataFrame(issues['labels'])
labels

                                               labels
0                                                  []
1   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...
2                                                  []
3                                                  []
4   [{'id': 32933285, 'node_id': 'MDU6TGFiZWwzMjkz...
5   [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...
6   [{'id': 48070600, 'node_id': 'MDU6TGFiZWw0ODA3...
7                                                  []
8   [{'id': 131473665, 'node_id': 'MDU6TGFiZWwxMzE...
9   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...
10  [{'id': 129350, 'node_id': 'MDU6TGFiZWwxMjkzNT...
11  [{'id': 129350, 'node_id': 'MDU6TGFiZWwxMjkzNT...
12  [{'id': 48070600, 'node_id': 'MDU6TGFiZWw0ODA3...
13  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...
14  [{'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOT...
15  [{'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOT...
16  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...
17  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...
18  [{'id': 685114413, 'node_id': 'MDU6TGFiZWw2ODU...
19  [{'id': 35818298, 'node_id': 'MDU6TGFiZWwzNTgx...
20  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...
21  [{'id': 8935311, 'node_id': 'MDU6TGFiZWw4OTM1M...
22  [{'id': 8935311, 'node_id': 'MDU6TGFiZWw4OTM1M...
23  [{'id': 732775912, 'node_id': 'MDU6TGFiZWw3MzI...
24  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...
25                                                 []
26  [{'id': 732775912, 'node_id': 'MDU6TGFiZWw3MzI...
27  [{'id': 78527356, 'node_id': 'MDU6TGFiZWw3ODUy...
28  [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...
29  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...

In [10]:
import pandas as pd
labels = pd.DataFrame(issues['labels'])
labels

                                               labels
0                                                  []
1   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...
2                                                  []
3                                                  []
4   [{'id': 32933285, 'node_id': 'MDU6TGFiZWwzMjkz...
5   [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...
6   [{'id': 48070600, 'node_id': 'MDU6TGFiZWw0ODA3...
7                                                  []
8   [{'id': 131473665, 'node_id': 'MDU6TGFiZWwxMzE...
9   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...
10  [{'id': 129350, 'node_id': 'MDU6TGFiZWwxMjkzNT...
11  [{'id': 129350, 'node_id': 'MDU6TGFiZWwxMjkzNT...
12  [{'id': 48070600, 'node_id': 'MDU6TGFiZWw0ODA3...
13  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...
14  [{'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOT...
15  [{'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOT...
16  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...
17  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...
18  [{'id': 685114413, 'node_id': 'MDU6TGFiZWw2ODU...
19  [{'id': 35818298, 'node_id': 'MDU6TGFiZWwzNTgx...
20  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...
21  [{'id': 8935311, 'node_id': 'MDU6TGFiZWw4OTM1M...
22  [{'id': 8935311, 'node_id': 'MDU6TGFiZWw4OTM1M...
23  [{'id': 732775912, 'node_id': 'MDU6TGFiZWw3MzI...
24  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...
25                                                 []
26  [{'id': 732775912, 'node_id': 'MDU6TGFiZWw3MzI...
27  [{'id': 78527356, 'node_id': 'MDU6TGFiZWw3ODUy...
28  [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...
29  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...

In [37]:
l=[]
for i in range(len(issues)):
    l.append(pd.DataFrame(issues['labels'][i]))
l

[Empty DataFrame
 Columns: []
 Index: [],
            id                   node_id  \
 0       76811      MDU6TGFiZWw3NjgxMQ==
 1  1465286368  MDU6TGFiZWwxNDY1Mjg2MzY4
 2    49182326  MDU6TGFiZWw0OTE4MjMyNg==
 3      211840      MDU6TGFiZWwyMTE4NDA=

                                                  url          name   color  \
 0  https://api.github.com/repos/pandas-dev/pandas...           Bug  e10c02
 1  https://api.github.com/repos/pandas-dev/pandas...  Constructors  d4c5f9
 2  https://api.github.com/repos/pandas-dev/pandas...        Sparse  009800
 3  https://api.github.com/repos/pandas-dev/pandas...    Timeseries  AFEEEE

    default                                   description
 0    False                                          None
 1    False  Series/DataFrame/Index/pd.array Constructors
 2    False                              Sparse Data Type
 3    False                                          None  ,
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
          id                   node_id  \
 0  32933285  MDU6TGFiZWwzMjkzMzI4NQ==
 1  48070600  MDU6TGFiZWw0ODA3MDYwMA==

                                                  url   name   color  default  \
 0  https://api.github.com/repos/pandas-dev/pandas...  Admin  DDDDDD    False
 1  https://api.github.com/repos/pandas-dev/pandas...     CI  a2bca7    False

                                          description
 0  Administrative tasks related to the pandas pro...
 1                  Related to Continuous Integration  ,
        id               node_id  \
 0  134699  MDU6TGFiZWwxMzQ2OTk=

                                                  url  name   color  default  \
 0  https://api.github.com/repos/pandas-dev/pandas...  Docs  3465A4    False

   description
 0        None  ,
          id                   node_id  \
 0  48070600  MDU6TGFiZWw0ODA3MDYwMA==
 1    127685      MDU6TGFiZWwxMjc2ODU=

                                                  url     name   color  \
 0  https://api.github.com/repos/pandas-dev/pandas...       CI  a2bca7
 1  https://api.github.com/repos/pandas-dev/pandas...  Testing  C4A000

    default                                        description
 0    False                  Related to Continuous Integration
 1    False  Custom testing functions or related to the tes...  ,
 Empty DataFrame
 Columns: []
 Index: [],
           id                   node_id  \
 0  131473665  MDU6TGFiZWwxMzE0NzM2NjU=

                                                  url     name   color  \
 0  https://api.github.com/repos/pandas-dev/pandas...  Release  006b75

    default description
 0    False        None  ,
            id                   node_id  \
 0       76811      MDU6TGFiZWw3NjgxMQ==
 1  1954720290  MDU6TGFiZWwxOTU0NzIwMjkw

                                                  url          name   color  \
 0  https://api.github.com/repos/pandas-dev/pandas...           Bug  e10c02
 1  https://api.github.com/repos/pandas-dev/pandas...  Needs Triage  0052cc

    default                                        description
 0    False                                               None
 1    False  Issue that has not been reviewed by a pandas t...  ,
        id               node_id  \
 0  129350  MDU6TGFiZWwxMjkzNTA=

                                                  url   name   color  default  \
 0  https://api.github.com/repos/pandas-dev/pandas...  Build  75507B    False

                              description
 0  Library building on various platforms  ,
        id               node_id  \
 0  129350  MDU6TGFiZWwxMjkzNTA=

                                                  url   name   color  default  \
 0  https://api.github.com/repos/pandas-dev/pandas...  Build  75507B    False

                              description
 0  Library building on various platforms  ,
          id                   node_id  \
 0  48070600  MDU6TGFiZWw0ODA3MDYwMA==

                                                  url name   color  default  \
 0  https://api.github.com/repos/pandas-dev/pandas...   CI  a2bca7    False

                          description
 0  Related to Continuous Integration  ,
            id                   node_id  \
 0       76811      MDU6TGFiZWw3NjgxMQ==
 1  1954720290  MDU6TGFiZWwxOTU0NzIwMjkw

                                                  url          name   color  \
 0  https://api.github.com/repos/pandas-dev/pandas...           Bug  e10c02
 1  https://api.github.com/repos/pandas-dev/pandas...  Needs Triage  0052cc

    default                                        description
 0    False                                               None
 1    False  Issue that has not been reviewed by a pandas t...  ,
            id                   node_id  \
 0  1954720290  MDU6TGFiZWwxOTU0NzIwMjkw
 1    34444536  MDU6TGFiZWwzNDQ0NDUzNg==

                                                  url            name   color  \
 0  https://api.github.com/repos/pandas-dev/pandas...    Needs Triage  0052cc
 1  https://api.github.com/repos/pandas-dev/pandas...  Usage Question  0052cc

    default                                        description
 0    False  Issue that has not been reviewed by a pandas t...
 1    False                                               None  ,
            id                   node_id  \
 0  1954720290  MDU6TGFiZWwxOTU0NzIwMjkw
 1    34444536  MDU6TGFiZWwzNDQ0NDUzNg==

                                                  url            name   color  \
 0  https://api.github.com/repos/pandas-dev/pandas...    Needs Triage  0052cc
 1  https://api.github.com/repos/pandas-dev/pandas...  Usage Question  0052cc

    default                                        description
 0    False  Issue that has not been reviewed by a pandas t...
 1    False                                               None  ,
            id                   node_id  \
 0       76811      MDU6TGFiZWw3NjgxMQ==
 1  1954720290  MDU6TGFiZWwxOTU0NzIwMjkw

                                                  url          name   color  \
 0  https://api.github.com/repos/pandas-dev/pandas...           Bug  e10c02
 1  https://api.github.com/repos/pandas-dev/pandas...  Needs Triage  0052cc

    default                                        description
 0    False                                               None
 1    False  Issue that has not been reviewed by a pandas t...  ,
            id                   node_id  \
 0       76811      MDU6TGFiZWw3NjgxMQ==
 1  1954720290  MDU6TGFiZWwxOTU0NzIwMjkw

                                                  url          name   color  \
 0  https://api.github.com/repos/pandas-dev/pandas...           Bug  e10c02
 1  https://api.github.com/repos/pandas-dev/pandas...  Needs Triage  0052cc

    default                                        description
 0    False                                               None
 1    False  Issue that has not been reviewed by a pandas t...  ,
           id                   node_id  \
 0  685114413  MDU6TGFiZWw2ODUxMTQ0MTM=
 1     127685      MDU6TGFiZWwxMjc2ODU=

                                                  url        name   color  \
 0  https://api.github.com/repos/pandas-dev/pandas...  IO Parquet  5319e7
 1  https://api.github.com/repos/pandas-dev/pandas...     Testing  C4A000

    default                                        description
 0    False                          parquet, feather, pyarrow
 1    False  Custom testing functions or related to the tes...  ,
          id                   node_id  \
 0  35818298  MDU6TGFiZWwzNTgxODI5OA==
 1  34444536  MDU6TGFiZWwzNDQ0NDUzNg==

                                                  url            name   color  \
 0  https://api.github.com/repos/pandas-dev/pandas...      API Design  AD7FA8
 1  https://api.github.com/repos/pandas-dev/pandas...  Usage Question  0052cc

    default description
 0    False        None
 1    False        None  ,
          id                   node_id  \
 0     76811      MDU6TGFiZWw3NjgxMQ==
 1  57522093  MDU6TGFiZWw1NzUyMjA5Mw==

                                                  url     name   color  \
 0  https://api.github.com/repos/pandas-dev/pandas...      Bug  e10c02
 1  https://api.github.com/repos/pandas-dev/pandas...  Strings  5319e7

    default                                 description
 0    False                                        None
 1    False  String extension data type and string data  ,
          id                   node_id  \
 0   8935311      MDU6TGFiZWw4OTM1MzEx
 1  32815646  MDU6TGFiZWwzMjgxNTY0Ng==

                                                  url         name   color  \
 0  https://api.github.com/repos/pandas-dev/pandas...  Performance  a10c02
 1  https://api.github.com/repos/pandas-dev/pandas...   Regression  e11d21

    default                                        description
 0    False              Memory or execution speed performance
 1    False  Functionality that used to work in a prior pan...  ,
          id                   node_id  \
 0   8935311      MDU6TGFiZWw4OTM1MzEx
 1  32815646  MDU6TGFiZWwzMjgxNTY0Ng==

                                                  url         name   color  \
 0  https://api.github.com/repos/pandas-dev/pandas...  Performance  a10c02
 1  https://api.github.com/repos/pandas-dev/pandas...   Regression  e11d21

    default                                        description
 0    False              Memory or execution speed performance
 1    False  Functionality that used to work in a prior pan...  ,
           id                   node_id  \
 0  732775912  MDU6TGFiZWw3MzI3NzU5MTI=
 1   32815646  MDU6TGFiZWwzMjgxNTY0Ng==

                                                  url        name   color  \
 0  https://api.github.com/repos/pandas-dev/pandas...   Benchmark  ae68cc
 1  https://api.github.com/repos/pandas-dev/pandas...  Regression  e11d21

    default                                        description
 0    False                       Performance (ASV) benchmarks
 1    False  Functionality that used to work in a prior pan...  ,
          id                   node_id  \
 0     76811      MDU6TGFiZWw3NjgxMQ==
 1  49254273  MDU6TGFiZWw0OTI1NDI3Mw==

                                                  url      name   color  \
 0  https://api.github.com/repos/pandas-dev/pandas...       Bug  e10c02
 1  https://api.github.com/repos/pandas-dev/pandas...  IO Excel  bfe5bf

    default           description
 0    False                  None
 1    False  read_excel, to_excel  ,
 Empty DataFrame
 Columns: []
 Index: [],
           id                   node_id  \
 0  732775912  MDU6TGFiZWw3MzI3NzU5MTI=

                                                  url       name   color  \
 0  https://api.github.com/repos/pandas-dev/pandas...  Benchmark  ae68cc

    default                   description
 0    False  Performance (ASV) benchmarks  ,
          id                   node_id  \
 0  78527356  MDU6TGFiZWw3ODUyNzM1Ng==
 1  31404521  MDU6TGFiZWwzMTQwNDUyMQ==
 2  49182326  MDU6TGFiZWw0OTE4MjMyNg==

                                                  url         name   color  \
 0  https://api.github.com/repos/pandas-dev/pandas...  Categorical  e11d21
 1  https://api.github.com/repos/pandas-dev/pandas...       Dtypes  e102d8
 2  https://api.github.com/repos/pandas-dev/pandas...       Sparse  009800

    default            description
 0    False  Categorical Data Type
 1    False                   None
 2    False       Sparse Data Type  ,
            id                   node_id  \
 0       76812      MDU6TGFiZWw3NjgxMg==
 1  1954720290  MDU6TGFiZWwxOTU0NzIwMjkw

                                                  url          name   color  \
 0  https://api.github.com/repos/pandas-dev/pandas...   Enhancement  4E9A06
 1  https://api.github.com/repos/pandas-dev/pandas...  Needs Triage  0052cc

    default                                        description
 0    False                                               None
 1    False  Issue that has not been reviewed by a pandas t...  ,
          id                   node_id  \
 0     76811      MDU6TGFiZWw3NjgxMQ==
 1  49182326  MDU6TGFiZWw0OTE4MjMyNg==

                                                  url    name   color  default  \
 0  https://api.github.com/repos/pandas-dev/pandas...     Bug  e10c02    False
 1  https://api.github.com/repos/pandas-dev/pandas...  Sparse  009800    False

         description
 0              None
 1  Sparse Data Type  ]

In [29]:
pd.DataFrame(issues['labels'][1])

,id,node_id,url,name,color,default,description
0,76811,MDU6TGFiZWw3NjgxMQ==,https://api.github.com/repos/pandas-dev/pandas...,Bug,e10c02,False,None
1,1465286368,MDU6TGFiZWwxNDY1Mjg2MzY4,https://api.github.com/repos/pandas-dev/pandas...,Constructors,d4c5f9,False,Series/DataFrame/Index/pd.array Constructors
2,49182326,MDU6TGFiZWw0OTE4MjMyNg==,https://api.github.com/repos/pandas-dev/pandas...,Sparse,009800,False,Sparse Data Type
3,211840,MDU6TGFiZWwyMTE4NDA=,https://api.github.com/repos/pandas-dev/pandas...,Timeseries,AFEEEE,False,None